services:
  # Backend Spring Boot Service (Docker)
  - type: web
    name: imagegenie-backend
    env: docker
    dockerfilePath: ./backend/image-service/Dockerfile
    dockerContext: ./backend/image-service
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_S3_BUCKET
        value: project-image-processing-service-bucket
      - key: DATABASE_URL
        fromDatabase:
          name: imagegenie-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend React Service (Docker)
  - type: web
    name: imagegenie-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://imagegenie-backend.onrender.com

databases:
  - name: imagegenie-db
    plan: free