services:
  # Backend Spring Boot Service
  - type: web
    name: imagegenie-backend
    env: java
    buildCommand: cd backend/image-service && mvn clean package -DskipTests
    startCommand: cd backend/image-service && java -jar target/image-service-0.0.1-SNAPSHOT.jar
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_S3_BUCKET
        value: project-image-processing-service-bucket
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: imagegenie-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: imagegenie-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: imagegenie-db
          property: password
      - key: JWT_SECRET
        generateValue: true

  # Frontend React Service
  - type: web
    name: imagegenie-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -p 10000
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://imagegenie-backend.onrender.com

databases:
  - name: imagegenie-db
    plan: free